#!/usr/bin/env python3
"""The 65816 opcodes this ROM actually contains, taken from the assembler.

WHY NOT A REFERENCE TABLE.  An interpreter built from a published opcode matrix
is only as good as the transcription, and a single wrong byte does not crash --
it decodes one instruction as another, desynchronises, and produces a trace that
looks like a bug in the port being judged.  There is a better source: ca65
assembled this ROM, so its own listings say exactly which byte it emitted for
every instruction in it.  That is ground truth for this ROM specifically, and
coverage is exact by construction -- an opcode absent from the listings is one
the ROM does not contain.

So OPCODES below is generated by `--regen`, which re-assembles the frozen sources
into a scratch directory with `-l` and reads the bytes back out.  It never writes
to platform/snes/build, and the ROM is not rebuilt.

The interpreter HARD-ERRORS on any byte not in this table.  That is deliberate
and is the strongest self-check available: if it ever trips, either the decoder
desynchronised -- a real bug, caught at the instruction that caused it rather
than a hundred frames later -- or the CPU is executing bytes that were assembled
as data, which is also a real bug.

Modes, as the interpreter's decoder names them:
    imp     implied                  acc     accumulator
    imm     immediate, WIDTH VARIES with the m/x flags -- the one place the
            instruction length is not a property of the opcode
    dp      direct page              abs     absolute
    dp_x    direct page indexed X    abs_x   absolute indexed X
    dp_y    direct page indexed Y    abs_y   absolute indexed Y
    ind_y   (dp),y                   lng     [dp]        lng_y   [dp],y
    rel     8-bit signed branch
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNES = ROOT / "platform" / "snes"

# opcode byte -> (mnemonic, mode).  Generated; see --regen.
OPCODES: dict[int, tuple[str, str]] = {
    0x09: ("ora", "imm"),   0x0A: ("asl", "acc"),   0x0B: ("phd", "imp"),
    0x10: ("bpl", "rel"),   0x18: ("clc", "imp"),   0x1A: ("inc", "acc"),
    0x1D: ("ora", "abs_x"), 0x20: ("jsr", "abs"),   0x25: ("and", "dp"),
    0x29: ("and", "imm"),   0x2B: ("pld", "imp"),   0x30: ("bmi", "rel"),
    0x38: ("sec", "imp"),   0x3A: ("dec", "acc"),   0x40: ("rti", "imp"),
    0x45: ("eor", "dp"),    0x48: ("pha", "imp"),   0x49: ("eor", "imm"),
    0x4A: ("lsr", "acc"),   0x4B: ("phk", "imp"),   0x4C: ("jmp", "abs"),
    0x58: ("cli", "imp"),   0x5A: ("phy", "imp"),   0x5B: ("tcd", "imp"),
    0x60: ("rts", "imp"),   0x64: ("stz", "dp"),    0x65: ("adc", "dp"),
    0x68: ("pla", "imp"),   0x69: ("adc", "imm"),   0x78: ("sei", "imp"),
    0x79: ("adc", "abs_y"), 0x7A: ("ply", "imp"),   0x7D: ("adc", "abs_x"),
    0x80: ("bra", "rel"),   0x84: ("sty", "dp"),    0x85: ("sta", "dp"),
    0x86: ("stx", "dp"),    0x88: ("dey", "imp"),   0x8A: ("txa", "imp"),
    0x8B: ("phb", "imp"),   0x8D: ("sta", "abs"),   0x8E: ("stx", "abs"),
    0x90: ("bcc", "rel"),   0x98: ("tya", "imp"),   0x99: ("sta", "abs_y"),
    0x9A: ("txs", "imp"),   0x9C: ("stz", "abs"),   0x9D: ("sta", "abs_x"),
    0x9E: ("stz", "abs_x"), 0xA0: ("ldy", "imm"),   0xA2: ("ldx", "imm"),
    0xA4: ("ldy", "dp"),    0xA5: ("lda", "dp"),    0xA6: ("ldx", "dp"),
    0xA7: ("lda", "lng"),   0xA8: ("tay", "imp"),   0xA9: ("lda", "imm"),
    0xAA: ("tax", "imp"),   0xAB: ("plb", "imp"),   0xAD: ("lda", "abs"),
    0xB0: ("bcs", "rel"),   0xB1: ("lda", "ind_y"), 0xB7: ("lda", "lng_y"),
    0xB9: ("lda", "abs_y"), 0xBD: ("lda", "abs_x"), 0xBE: ("ldx", "abs_y"),
    0xC0: ("cpy", "imm"),   0xC2: ("rep", "imm8"),  0xC4: ("cpy", "dp"),
    0xC5: ("cmp", "dp"),    0xC6: ("dec", "dp"),    0xC8: ("iny", "imp"),
    0xC9: ("cmp", "imm"),   0xD0: ("bne", "rel"),   0xDA: ("phx", "imp"),
    0xE0: ("cpx", "imm"),   0xE2: ("sep", "imm8"),  0xE4: ("cpx", "dp"),
    0xE5: ("sbc", "dp"),    0xE6: ("inc", "dp"),    0xE8: ("inx", "imp"),
    0xE9: ("sbc", "imm"),   0xEB: ("xba", "imp"),   0xF0: ("beq", "rel"),
    0xF6: ("inc", "dp_x"),  0xFA: ("plx", "imp"),   0xFB: ("xce", "imp"),
    0xFD: ("sbc", "abs_x"), 0xFE: ("inc", "abs_x"),
    # ROR IS IN THE ROM AND NO SOURCE LINE SAYS SO.  It comes from the ASR1
    # macro (macros.inc:49-52), `cmp #$8000 / ror a` -- the standard 65816
    # arithmetic shift right, which is why grid.h's asr1() floors.  A macro
    # invocation assembles to several instructions on ONE listing line whose text
    # is the macro's name, so scan_listings() cannot attribute it and skips the
    # line whole.  check() now decodes every byte run to catch exactly this, and
    # this entry is what it was missing.  Found the hard way: the interpreter
    # read `cmp #$8000` as a 16-bit immediate, which it is, and then hit $6A.
    0x6A: ("ror", "acc"),
}

# How many bytes follow the opcode.  `imm` is None because it depends on the m
# or x flag in force AT THAT MOMENT -- the one thing about instruction length
# that is not a property of the opcode, and the reason check_modes.py exists.
FIXED_LEN = {
    "imp": 0, "acc": 0, "imm8": 1, "rel": 1,
    "dp": 1, "dp_x": 1, "dp_y": 1, "ind_y": 1, "lng": 1, "lng_y": 1,
    "abs": 2, "abs_x": 2, "abs_y": 2,
}

# Which flag decides an immediate's width: 'm' for the accumulator, 'x' for the
# index registers.  cpx/cpy follow x, everything else here follows m.
IMM_WIDTH_FLAG = {"ldx": "x", "ldy": "x", "cpx": "x", "cpy": "x"}


def operand_len(mnemonic: str, mode: str, m: int, x: int) -> int:
    if mode != "imm":
        return FIXED_LEN[mode]
    flag = IMM_WIDTH_FLAG.get(mnemonic, "m")
    return 1 if (m if flag == "m" else x) else 2


_LINE = re.compile(r"^[0-9A-F]{6}r?\s+\d+\s{2}((?:[0-9A-Frx]{2} )+)\s*(.*)$")
_MN = re.compile(r"^([a-z]{3})(?:\s+(.*?))?\s*(?:;.*)?$")
_SKIP = {"res", "byte", "word", "addr", "asci", "incb", "dbyt", "faraddr"}
# A branch's operand is a label, which looks exactly like an absolute address in
# the source text; only the mnemonic says it is an 8-bit signed displacement.
_BRANCH = {"bcc", "bcs", "beq", "bmi", "bne", "bpl", "bvc", "bvs", "bra"}


def _shape(arg: str, nbytes: int) -> str:
    a = arg.strip()
    if not a:
        return "imp"
    if a == "a":
        return "acc"
    if a.startswith("#"):
        return "imm"
    if re.match(r"^\(.*\),\s*y$", a):
        return "ind_y"
    if re.match(r"^\[.*\],\s*y$", a):
        return "lng_y"
    if re.match(r"^\[.*\]$", a):
        return "lng"
    if a.endswith(",x"):
        return "abs_x" if nbytes == 3 else "dp_x"
    if a.endswith(",y"):
        return "abs_y" if nbytes == 3 else "dp_y"
    return "abs" if nbytes == 3 else "dp"


def scan_listings() -> dict[int, set[tuple[str, str]]]:
    """Re-assemble the frozen sources with -l and read every opcode back out.

    Writes only into a temporary directory and sends the object file to
    /dev/null: platform/snes/build is not touched and the ROM is not rebuilt.
    """
    found: dict[int, set[tuple[str, str]]] = {}
    with tempfile.TemporaryDirectory() as tmp:
        for src in sorted((SNES / "src").glob("*.s")):
            lst = Path(tmp) / (src.stem + ".lst")
            r = subprocess.run(
                ["ca65", "--cpu", "65816", "-I", "src", "--bin-include-dir",
                 str(ROOT), "-g", "-l", str(lst), "-o", "/dev/null", str(src)],
                cwd=SNES, capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit(f"ca65 failed on {src.name}:\n{r.stderr}")
            for line in lst.read_text().splitlines():
                m = _LINE.match(line)
                if not m:
                    continue
                raw = m.group(1).split()
                mm = _MN.match(m.group(2).strip())
                if not mm or mm.group(1) in _SKIP:
                    continue
                mnem, arg = mm.group(1), mm.group(2) or ""
                if mnem in ("rep", "sep"):
                    mode = "imm8"
                elif mnem in _BRANCH:
                    mode = "rel"
                else:
                    mode = _shape(arg, len(raw))
                found.setdefault(int(raw[0], 16), set()).add((mnem, mode))
    return found


def decodes(raw: list[str]) -> bool:
    """Can this byte run be read as a whole number of instructions?

    An immediate's width is not in its opcode, so the walk BACKTRACKS over both
    possibilities rather than guessing -- a guess produces a bogus "missing
    opcode" for every macro that mixes `lda #<x` with `lda #.loword(x)`, which
    is most of the DMA ones.  A relocatable byte (`rr`) ends the run: the
    assembler does not know its value yet and neither can this.
    """
    def walk(i: int) -> bool:
        if i >= len(raw):
            return True
        try:
            b = int(raw[i], 16)
        except ValueError:
            return True                 # `rr`: nothing further is knowable
        ent = OPCODES.get(b)
        if ent is None:
            return False
        mnem, mode = ent
        if mode == "imm":
            return walk(i + 2) or walk(i + 3)
        return walk(i + 1 + FIXED_LEN[mode])
    return walk(0)


def audit_runs() -> int:
    """Decode every byte the assembler emitted, and report what will not decode.

    scan_listings() can only attribute lines whose text IS an instruction.  A
    macro puts several instructions on one line under the macro's name, so those
    lines are skipped -- and an opcode that appears ONLY inside a macro is then
    absent from the table with nothing to notice.  That is how `ror` went
    missing.

    This walks the raw byte runs instead and consumes them with the table.  A
    leftover byte is an opcode the ROM contains and the table does not, whatever
    the source text around it looked like.
    """
    missing: dict[str, int] = {}
    # ONLY the lines scan_listings() cannot attribute, which is exactly where the
    # gap can hide: a MACRO INVOCATION.  Its listing text is the macro's name --
    # an upper-case identifier, never a directive and never a lower-case
    # mnemonic -- and its byte run is however many instructions the macro
    # expanded to.  Auditing every line instead would try to decode `.byte`
    # tables as code, which is meaningless.
    macro = re.compile(r"^[A-Z][A-Z0-9_]*\b")
    with tempfile.TemporaryDirectory() as tmp:
        for src in sorted((SNES / "src").glob("*.s")):
            lst = Path(tmp) / (src.stem + ".lst")
            subprocess.run(
                ["ca65", "--cpu", "65816", "-I", "src", "--bin-include-dir",
                 str(ROOT), "-g", "-l", str(lst), "-o", "/dev/null", str(src)],
                cwd=SNES, capture_output=True, text=True, check=True)
            for line in lst.read_text().splitlines():
                m = _LINE.match(line)
                if not m:
                    continue
                text = m.group(2).strip()
                if not macro.match(text):
                    continue
                # A macro with a quoted argument emits DATA, not instructions --
                # TXTSTR lays out a HUD string.  Decoding it as code is
                # meaningless, and it is the one honest way to tell the two
                # kinds of macro apart from a listing alone.
                if '"' in text:
                    continue
                raw = m.group(1).split()
                if not decodes(raw):
                    missing[line] = missing.get(line, 0) + 1
    for line, n in sorted(missing.items()):
        print(f"  a macro expanded to bytes the table cannot decode "
              f"({n} time(s)):\n      {line.strip()}")
    return 1 if missing else 0


def check() -> int:
    """Does the table above still match what the assembler emits?"""
    found = scan_listings()
    bad = 0
    for b, entries in sorted(found.items()):
        if len(entries) > 1:
            print(f"  {b:02X} assembles as more than one thing: {sorted(entries)}")
            bad += 1
            continue
        got = next(iter(entries))
        want = OPCODES.get(b)
        if want is None:
            print(f"  {b:02X} {got[0]} {got[1]} is in the ROM and NOT in the table")
            bad += 1
        elif want != got:
            print(f"  {b:02X} table says {want}, the assembler emits {got}")
            bad += 1
    for b in sorted(set(OPCODES) - set(found)):
        if b == 0x6A:
            continue        # macro-only; audit_runs() is what covers it
        print(f"  {b:02X} {OPCODES[b]} is in the table and NOT in the ROM")
        bad += 1
    # ...and the same again from the other direction, over the raw bytes, so an
    # opcode hidden inside a macro cannot slip past the way `ror` did.
    bad += audit_runs()
    if bad:
        print(f"opcodes: {bad} disagreement(s) with the assembler")
        return 1
    print(f"opcodes ok: {len(OPCODES)} bytes, and every byte the assembler "
          f"emitted decodes with them")
    return 0


def regen() -> int:
    found = scan_listings()
    for b in sorted(found):
        entries = found[b]
        if len(entries) != 1:
            raise SystemExit(f"{b:02X} is ambiguous: {sorted(entries)}")
        mnem, mode = next(iter(entries))
        print(f"    0x{b:02X}: ({mnem!r}, {mode!r}),")
    return 0


if __name__ == "__main__":
    sys.exit(regen() if "--regen" in sys.argv else check())
